/**
 * Tier A/B curated seeds — reliability still mostly unknown except implemented.
 */

import type { SourceIntelligence } from "./types";

function s(
  partial: Omit<SourceIntelligence, "marketsSupported"> & {
    marketsSupported?: string[];
  },
): SourceIntelligence {
  return {
    ...partial,
    marketsSupported: partial.marketsSupported ?? [],
  };
}

/** Tier A — professional / official (often commercial; still catalogued). */
export const TIER_A_SEEDS: SourceIntelligence[] = [
  s({
    id: "stats-perform-opta",
    name: "Stats Perform / Opta",
    url: "https://www.statsperform.com",
    sports: ["football", "multi"],
    capabilities: ["event_stats", "player_stats", "tracking", "lineups"],
    categories: ["PRIMARY_DATA_PROVIDER", "TRACKING", "EVENT_DATA"],
    role: "UPSTREAM",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    historicalDepth: "decades",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: true,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "stats_perform",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
    marketsSupported: ["result", "total_goals", "corners", "cards", "player_goals"],
  }),
  s({
    id: "sportradar",
    name: "Sportradar",
    url: "https://sportradar.com",
    sports: ["multi"],
    capabilities: ["fixtures", "results", "odds", "event_stats"],
    categories: ["PRIMARY_DATA_PROVIDER", "ODDS_PROVIDER"],
    role: "PROVIDER",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    live: true,
    odds: true,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "sportradar",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "statsbomb",
    name: "StatsBomb",
    url: "https://statsbomb.com",
    sports: ["football"],
    capabilities: ["event_stats", "player_stats", "advanced_stats"],
    categories: ["PRIMARY_DATA_PROVIDER", "RESEARCH"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    historicalDepth: "open_data_subset",
    live: false,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "statsbomb",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
    marketsSupported: ["result", "total_goals", "player_shots", "player_goals"],
  }),
  s({
    id: "wyscout",
    name: "Wyscout",
    url: "https://wyscout.com",
    sports: ["football"],
    capabilities: ["player_stats", "event_stats", "lineups"],
    categories: ["PRIMARY_DATA_PROVIDER", "PLAYER_DATA"],
    role: "PROVIDER",
    geography: ["global"],
    languages: ["en", "it"],
    access: "licensed_feed",
    live: false,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "hudl_wyscout",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "skillcorner",
    name: "SkillCorner",
    url: "https://www.skillcorner.com",
    sports: ["football"],
    capabilities: ["tracking", "player_stats"],
    categories: ["TRACKING", "PRIMARY_DATA_PROVIDER"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: true,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "skillcorner",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "img-arena",
    name: "IMG Arena",
    url: "https://www.imgarena.com",
    sports: ["multi"],
    capabilities: ["fixtures", "results", "odds"],
    categories: ["PRIMARY_DATA_PROVIDER", "ODDS_PROVIDER"],
    role: "PROVIDER",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    live: true,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "img_arena",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "betgenius",
    name: "Betgenius",
    url: "https://www.geniusports.com",
    sports: ["multi"],
    capabilities: ["odds", "fixtures", "event_stats"],
    categories: ["ODDS_PROVIDER", "PRIMARY_DATA_PROVIDER"],
    role: "PROVIDER",
    geography: ["global"],
    languages: ["en"],
    access: "licensed_feed",
    live: true,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "genius_sports",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "don-best",
    name: "Don Best",
    url: "https://donbest.com",
    sports: ["multi"],
    capabilities: ["odds", "historical_odds"],
    categories: ["ODDS_PROVIDER"],
    role: "PROVIDER",
    geography: ["us"],
    languages: ["en"],
    access: "licensed_feed",
    live: true,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "don_best",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "pinnacle",
    name: "Pinnacle",
    url: "https://www.pinnacle.com",
    sports: ["multi"],
    capabilities: ["odds", "historical_odds"],
    categories: ["BOOKMAKER"],
    role: "BOOKMAKER",
    geography: ["global"],
    languages: ["en"],
    access: "bookmaker",
    live: true,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "pinnacle",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
    marketsSupported: ["result", "asian_handicap", "total_goals", "both_teams_to_score"],
  }),
  s({
    id: "betfair-exchange",
    name: "Betfair Exchange",
    url: "https://www.betfair.com/exchange",
    sports: ["multi"],
    capabilities: ["odds", "historical_odds"],
    categories: ["EXCHANGE"],
    role: "EXCHANGE",
    geography: ["global"],
    languages: ["en"],
    access: "exchange",
    live: true,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "betfair",
    licensing: "commercial",
    reliability: "unknown",
    implementation: "not_implemented",
    tier: "A",
  }),
  s({
    id: "uefa",
    name: "UEFA",
    url: "https://www.uefa.com",
    sports: ["football"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["europe"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "uefa_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "fifa",
    name: "FIFA",
    url: "https://www.fifa.com",
    sports: ["football"],
    capabilities: ["fixtures", "results"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: false,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "fifa_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "atp",
    name: "ATP Tour",
    url: "https://www.atptour.com",
    sports: ["tennis"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: true,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "atp_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "wta",
    name: "WTA",
    url: "https://www.wtatennis.com",
    sports: ["tennis"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: true,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "wta_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "nba",
    name: "NBA",
    url: "https://www.nba.com",
    sports: ["basketball"],
    capabilities: ["fixtures", "results", "player_stats", "event_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_api",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "nba_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "mlb",
    name: "MLB",
    url: "https://www.mlb.com",
    sports: ["baseball"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_api",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "mlb_official",
    licensing: "free_api",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "nhl",
    name: "NHL",
    url: "https://www.nhl.com",
    sports: ["ice_hockey"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["us", "ca"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "nhl_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "nfl",
    name: "NFL",
    url: "https://www.nfl.com",
    sports: ["american_football"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "nfl_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "pga-tour",
    name: "PGA Tour",
    url: "https://www.pgatour.com",
    sports: ["golf"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["us", "global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "pga_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "formula1",
    name: "Formula 1",
    url: "https://www.formula1.com",
    sports: ["formula_1"],
    capabilities: ["fixtures", "results"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "f1_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "motogp",
    name: "MotoGP",
    url: "https://www.motogp.com",
    sports: ["motorsport"],
    capabilities: ["fixtures", "results"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "motogp_official",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "world-rugby",
    name: "World Rugby",
    url: "https://www.world.rugby",
    sports: ["rugby"],
    capabilities: ["fixtures", "results"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: false,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "world_rugby",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
  s({
    id: "world-athletics",
    name: "World Athletics",
    url: "https://worldathletics.org",
    sports: ["athletics"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: true,
    temporalPrecision: "unknown",
    independenceCluster: "world_athletics",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "A",
  }),
];

/** Tier B — accessible / €0-friendly candidates. */
export const TIER_B_SEEDS: SourceIntelligence[] = [
  s({
    id: "football-data-org",
    name: "football-data.org",
    url: "https://www.football-data.org",
    sports: ["football"],
    capabilities: ["fixtures", "results"],
    categories: ["SECONDARY_DATA_PROVIDER", "HISTORICAL_DATASET"],
    role: "PROVIDER",
    geography: ["europe"],
    languages: ["en"],
    access: "public_api",
    historicalDepth: "seasons",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "football_data_org",
    licensing: "free_api",
    reliability: "unverified",
    implementation: "implemented",
    tier: "B",
    marketsSupported: ["result"],
  }),
  s({
    id: "football-data-co-uk",
    name: "football-data.co.uk",
    url: "https://www.football-data.co.uk",
    sports: ["football"],
    capabilities: ["results", "odds", "historical_odds"],
    categories: ["HISTORICAL_DATASET", "ODDS_PROVIDER"],
    role: "SOURCE",
    geography: ["europe"],
    languages: ["en"],
    access: "dataset",
    historicalDepth: "20y+",
    live: false,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "dataset_window",
    independenceCluster: "football_data_co_uk",
    licensing: "open",
    reliability: "unverified",
    implementation: "blocked",
    tier: "B",
    marketsSupported: ["result", "total_goals", "asian_handicap"],
  }),
  s({
    id: "clubelo",
    name: "ClubElo",
    url: "http://clubelo.com",
    sports: ["football"],
    capabilities: ["elo"],
    categories: ["RESEARCH", "DATABASE"],
    role: "SOURCE",
    geography: ["europe"],
    languages: ["en"],
    access: "dataset",
    historicalDepth: "long",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "date",
    independenceCluster: "clubelo",
    licensing: "open",
    reliability: "unverified",
    implementation: "implemented",
    tier: "B",
  }),
  s({
    id: "fbref",
    name: "FBref",
    url: "https://fbref.com",
    sports: ["football"],
    capabilities: ["player_stats", "event_stats", "advanced_stats"],
    categories: ["DATABASE", "PLAYER_DATA"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    historicalDepth: "multi_season",
    live: false,
    odds: false,
    injuries: false,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    upstream: ["statsbomb"],
    independenceCluster: "sports_reference",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
    marketsSupported: ["player_goals", "player_shots", "player_assists", "player_cards"],
  }),
  s({
    id: "understat",
    name: "Understat",
    url: "https://understat.com",
    sports: ["football"],
    capabilities: ["advanced_stats", "player_stats"],
    categories: ["DATABASE", "RESEARCH"],
    role: "SOURCE",
    geography: ["europe"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "understat",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "baseball-reference",
    name: "Baseball Reference",
    url: "https://www.baseball-reference.com",
    sports: ["baseball"],
    capabilities: ["results", "player_stats", "event_stats"],
    categories: ["DATABASE"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "sports_reference",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "basketball-reference",
    name: "Basketball Reference",
    url: "https://www.basketball-reference.com",
    sports: ["basketball"],
    capabilities: ["results", "player_stats"],
    categories: ["DATABASE"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "sports_reference",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "hockey-reference",
    name: "Hockey Reference",
    url: "https://www.hockey-reference.com",
    sports: ["ice_hockey"],
    capabilities: ["results", "player_stats"],
    categories: ["DATABASE"],
    role: "SOURCE",
    geography: ["us", "ca"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "sports_reference",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "pro-football-reference",
    name: "Pro Football Reference",
    url: "https://www.pro-football-reference.com",
    sports: ["american_football"],
    capabilities: ["results", "player_stats"],
    categories: ["DATABASE"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "sports_reference",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "ergast-f1",
    name: "Ergast F1 API",
    url: "https://ergast.com/mrd/",
    sports: ["formula_1"],
    capabilities: ["results", "fixtures"],
    categories: ["HISTORICAL_DATASET", "DATABASE"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_api",
    historicalDepth: "1950+",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "date",
    independenceCluster: "ergast",
    licensing: "open",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "openligadb",
    name: "OpenLigaDB",
    url: "https://www.openligadb.de",
    sports: ["football"],
    capabilities: ["fixtures", "results"],
    categories: ["HISTORICAL_DATASET"],
    role: "SOURCE",
    geography: ["de"],
    languages: ["de", "en"],
    access: "public_api",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "openligadb",
    licensing: "open",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "collegefootballdata",
    name: "CollegeFootballData",
    url: "https://collegefootballdata.com",
    sports: ["american_football"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["HISTORICAL_DATASET", "ACADEMIC"],
    role: "SOURCE",
    geography: ["us"],
    languages: ["en"],
    access: "public_api",
    live: false,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "cfbd",
    licensing: "free_api",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "mlb-stats-api",
    name: "MLB Stats API",
    url: "https://statsapi.mlb.com",
    sports: ["baseball"],
    capabilities: ["fixtures", "results", "player_stats"],
    categories: ["OFFICIAL", "PRIMARY_DATA_PROVIDER"],
    role: "PROVIDER",
    geography: ["us"],
    languages: ["en"],
    access: "public_api",
    live: true,
    odds: false,
    injuries: true,
    lineups: true,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    upstream: ["mlb"],
    independenceCluster: "mlb_official",
    licensing: "free_api",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "procyclingstats",
    name: "ProCyclingStats",
    url: "https://www.procyclingstats.com",
    sports: ["cycling"],
    capabilities: ["results", "player_stats"],
    categories: ["DATABASE", "COMMUNITY"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_web",
    live: false,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: true,
    eventStats: true,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "procyclingstats",
    licensing: "unknown",
    reliability: "unknown",
    implementation: "candidate",
    tier: "B",
  }),
  s({
    id: "open-meteo",
    name: "Open-Meteo",
    url: "https://open-meteo.com",
    sports: ["multi"],
    capabilities: ["weather"],
    categories: ["WEATHER"],
    role: "SOURCE",
    geography: ["global"],
    languages: ["en"],
    access: "public_api",
    live: true,
    odds: false,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "minute",
    independenceCluster: "open_meteo",
    licensing: "open",
    reliability: "unknown",
    implementation: "implemented",
    tier: "B",
  }),
  s({
    id: "club-football-match-data",
    name: "Club-Football-Match-Data",
    url: "https://github.com/xgabora/Club-Football-Match-Data",
    sports: ["football"],
    capabilities: ["results", "odds", "elo", "historical_odds"],
    categories: ["HISTORICAL_DATASET", "SECONDARY_DATA_PROVIDER"],
    role: "SOURCE",
    geography: ["europe"],
    languages: ["en"],
    access: "dataset",
    historicalDepth: "large",
    live: false,
    odds: true,
    injuries: false,
    lineups: false,
    playerStats: false,
    eventStats: false,
    tracking: false,
    news: false,
    temporalPrecision: "unknown",
    independenceCluster: "club_football_match_data",
    licensing: "research",
    reliability: "unverified",
    implementation: "implemented",
    tier: "B",
    marketsSupported: ["result"],
  }),
];
