import type { FeatureDefinition } from "@/domain/features/types";

/**
 * Typed feature provenance registry.
 * No arbitrary reliability scores — status is READY/PARTIAL/BLOCKED/FORBIDDEN only.
 */
export const FEATURE_REGISTRY: readonly FeatureDefinition[] = Object.freeze([
  {
    id: "form_3_overall",
    name: "Form 3 (overall)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Points from previous 3 completed matches for the team (current excluded).",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_points_window_k=3_side=overall",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "form_5_overall",
    name: "Form 5 (overall)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Points from previous 5 completed matches (current excluded).",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_points_window_k=5_side=overall",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "form_10_overall",
    name: "Form 10 (overall)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Points from previous 10 completed matches (current excluded).",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_points_window_k=10_side=overall",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "form_5_home",
    name: "Home form 5",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Points from previous 5 home matches (current excluded).",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_points_window_k=5_side=home",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "form_5_away",
    name: "Away form 5",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Points from previous 5 away matches (current excluded).",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_points_window_k=5_side=away",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "goals_for_5",
    name: "Goals for (last 5)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Goals scored in previous 5 matches.",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_sum_goals_for_k=5",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "goals_against_5",
    name: "Goals against (last 5)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Goals conceded in previous 5 matches.",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_sum_goals_against_k=5",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "shots_for_5",
    name: "Shots for (last 5)",
    sport: "football",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Shots in previous 5 matches when stats available; missing stays missing.",
    requiredInputs: ["historical_matches", "team_id", "as_of"],
    reconstructionMethod: "lagged_sum_shots_for_k=5",
    leakageRisk: "low",
    status: "PARTIAL",
  },
  {
    id: "rest_days",
    name: "Rest days",
    sport: "*",
    source: "reconstructed_results",
    sourceRole: "DERIVED",
    temporalClass: "RECONSTRUCTED_STRICT",
    description: "Days since previous completed match for the team (same sport history).",
    requiredInputs: ["historical_matches", "team_id", "event_kickoff", "as_of"],
    reconstructionMethod: "days_since_previous_result_available",
    leakageRisk: "medium",
    status: "PARTIAL",
  },
  {
    id: "home_advantage_flag",
    name: "Home venue flag",
    sport: "*",
    source: "event_identity",
    sourceRole: "PRIMARY",
    temporalClass: "STRICT",
    description: "Whether the team is designated home for the event (identity, not strength).",
    requiredInputs: ["event"],
    reconstructionMethod: "event_home_team_id_equality",
    leakageRisk: "none",
    status: "READY",
  },
  {
    id: "home_elo",
    name: "Home Elo",
    sport: "football",
    source: "clubelo",
    sourceRole: "PRIMARY",
    temporalClass: "DATASET_WINDOW",
    description: "Latest official ClubElo snapshot available at asOf.",
    requiredInputs: ["elo_snapshots", "home_team_key", "as_of"],
    reconstructionMethod: "latest_snapshot_available_at_le_asof_official_only",
    leakageRisk: "medium",
    status: "PARTIAL",
  },
  {
    id: "away_elo",
    name: "Away Elo",
    sport: "football",
    source: "clubelo",
    sourceRole: "PRIMARY",
    temporalClass: "DATASET_WINDOW",
    description: "Latest official ClubElo snapshot available at asOf.",
    requiredInputs: ["elo_snapshots", "away_team_key", "as_of"],
    reconstructionMethod: "latest_snapshot_available_at_le_asof_official_only",
    leakageRisk: "medium",
    status: "PARTIAL",
  },
  {
    id: "elo_difference",
    name: "Elo difference",
    sport: "football",
    source: "clubelo",
    sourceRole: "DERIVED",
    temporalClass: "DATASET_WINDOW",
    description: "home_elo - away_elo when both STRICT/DATASET_WINDOW official.",
    requiredInputs: ["home_elo", "away_elo"],
    reconstructionMethod: "subtract",
    leakageRisk: "medium",
    status: "PARTIAL",
  },
  {
    id: "elo_expected_probability",
    name: "Elo expected home win prob (2-way)",
    sport: "football",
    source: "clubelo",
    sourceRole: "DERIVED",
    temporalClass: "DATASET_WINDOW",
    description: "Standard Elo expected score 1/(1+10^(-(home-away)/400)). Not a full 1X2 model.",
    requiredInputs: ["home_elo", "away_elo"],
    reconstructionMethod: "elo_logistic_400",
    leakageRisk: "medium",
    status: "PARTIAL",
  },
  {
    id: "market_implied_probability",
    name: "Market implied probability",
    sport: "*",
    source: "market_snapshots",
    sourceRole: "PRIMARY",
    temporalClass: "STRICT",
    description: "Implied probs from bookmaker odds available at asOf.",
    requiredInputs: ["market_snapshots", "as_of"],
    reconstructionMethod: "1/odds from as-of snapshots",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "market_overround",
    name: "Market overround",
    sport: "*",
    source: "market_snapshots",
    sourceRole: "DERIVED",
    temporalClass: "STRICT",
    description: "Sum of implied probs - 1 for a 1X2 book at asOf.",
    requiredInputs: ["market_snapshots", "as_of"],
    reconstructionMethod: "computeOverround",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "bookmaker_disagreement",
    name: "Bookmaker disagreement",
    sport: "*",
    source: "market_snapshots",
    sourceRole: "DERIVED",
    temporalClass: "STRICT",
    description: "Min/max/mean/median/dispersion across books at asOf — never a single silent pick.",
    requiredInputs: ["market_snapshots", "as_of"],
    reconstructionMethod: "cross_book_dispersion_v1",
    leakageRisk: "low",
    status: "READY",
  },
  {
    id: "opening_closing_movement",
    name: "Opening to closing movement",
    sport: "*",
    source: "market_snapshots",
    sourceRole: "DERIVED",
    temporalClass: "UNKNOWN",
    description: "Requires closing observation; FORBIDDEN for decisions before close.",
    requiredInputs: ["opening", "closing"],
    reconstructionMethod: "openCloseMovement",
    leakageRisk: "high",
    status: "BLOCKED",
  },
  {
    id: "cluster_c_star",
    name: "Club Football C_* clusters",
    sport: "football",
    source: "club-football-match-data",
    sourceRole: "BENCHMARK",
    temporalClass: "FORBIDDEN",
    description: "Author-derived clusters; excluded from STRICT_AS_OF.",
    requiredInputs: [],
    reconstructionMethod: "none",
    leakageRisk: "certain",
    status: "FORBIDDEN",
  },
  {
    id: "pack_form_blind",
    name: "Upstream Form* columns (blind use)",
    sport: "football",
    source: "club-football-match-data",
    sourceRole: "BENCHMARK",
    temporalClass: "UNKNOWN",
    description: "Do not use pack Form* blindly — reconstruct with our form engine.",
    requiredInputs: [],
    reconstructionMethod: "use_form_engine_instead",
    leakageRisk: "medium",
    status: "BLOCKED",
  },
  {
    id: "provisional_elo",
    name: "Provisional Elo continuation",
    sport: "football",
    source: "club-football-match-data",
    sourceRole: "BENCHMARK",
    temporalClass: "FORBIDDEN",
    description: "Author continuation after ClubElo cutoff — not STRICT_AS_OF.",
    requiredInputs: [],
    reconstructionMethod: "blocked",
    leakageRisk: "high",
    status: "FORBIDDEN",
  },
]);

export function getFeatureDefinition(id: string): FeatureDefinition | undefined {
  return FEATURE_REGISTRY.find((f) => f.id === id);
}

export function listFeaturesByStatus(
  status: FeatureDefinition["status"],
): FeatureDefinition[] {
  return FEATURE_REGISTRY.filter((f) => f.status === status);
}

export function listForbiddenFeatures(): FeatureDefinition[] {
  return FEATURE_REGISTRY.filter(
    (f) => f.temporalClass === "FORBIDDEN" || f.status === "FORBIDDEN",
  );
}
