import { getSport } from "../sports/catalog";
import type { EventType } from "../sports/types";
import type {
  MarketDefinition,
  MarketReadiness,
  MarketType,
} from "./types";

function market(definition: MarketDefinition): MarketDefinition {
  return Object.freeze({
    ...definition,
    selections: Object.freeze([...definition.selections]),
    applicableEventTypes: Object.freeze([...definition.applicableEventTypes]),
  });
}

/**
 * Extended taxonomy. readiness=CATALOG_CAPABILITY unless noted.
 * Never claim MODEL_READY without outcome + temporal + feature policy.
 */
const MARKETS: readonly MarketDefinition[] = Object.freeze([
  // --- Legacy / cross-sport generics (keep ids for existing callers) ---
  market({
    id: "winner",
    name: "Winner",
    sport: "*",
    family: "match_result",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "n_way",
    applicableEventTypes: [
      "team_vs_team",
      "individual_vs_individual",
      "race",
      "tournament",
      "match",
    ],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "draw",
    name: "Draw",
    sport: "*",
    family: "match_result",
    selections: ["YES", "NO"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "moneyline",
    name: "Moneyline",
    sport: "*",
    family: "match_result",
    selections: ["HOME", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["team_vs_team", "individual_vs_individual", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "spread",
    name: "Spread",
    sport: "*",
    family: "handicap",
    selections: ["HOME", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "total",
    name: "Total",
    sport: "*",
    family: "goals",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: [
      "team_vs_team",
      "individual_vs_individual",
      "match",
      "race",
    ],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "handicap",
    name: "Handicap",
    sport: "*",
    family: "handicap",
    selections: ["HOME", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "individual_vs_individual", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "set_winner",
    name: "Set winner",
    sport: "tennis",
    family: "match_result",
    selections: ["HOME", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["individual_vs_individual", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "game_winner",
    name: "Game winner",
    sport: "tennis",
    family: "match_result",
    selections: ["HOME", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["individual_vs_individual", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "race_winner",
    name: "Race winner",
    sport: "formula-1",
    family: "match_result",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "n_way",
    applicableEventTypes: ["race"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "podium",
    name: "Podium",
    sport: "formula-1",
    family: "other",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "n_way",
    applicableEventTypes: ["race"],
    readiness: "CATALOG_CAPABILITY",
  }),

  // --- Football-specific catalogue capabilities ---
  market({
    id: "result",
    name: "Full-time result (1X2)",
    sport: "football",
    family: "match_result",
    selections: ["HOME", "DRAW", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "ternary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
    notes: "Observed via market_snapshots market_type=winner in current Neon path",
  }),
  market({
    id: "double_chance",
    name: "Double chance",
    sport: "football",
    family: "match_result",
    selections: ["HOME_OR_DRAW", "DRAW_OR_AWAY", "HOME_OR_AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "ternary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "draw_no_bet",
    name: "Draw no bet",
    sport: "football",
    family: "match_result",
    selections: ["HOME", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "total_goals",
    name: "Total goals",
    sport: "football",
    family: "goals",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
    notes: "Observed as Over25/Under25 in FD.co.uk / Club Football pack (line=2.5)",
  }),
  market({
    id: "team_total_goals",
    name: "Team total goals",
    sport: "football",
    family: "goals",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: true,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "asian_handicap",
    name: "Asian handicap",
    sport: "football",
    family: "handicap",
    selections: ["HOME", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "european_handicap",
    name: "European handicap",
    sport: "football",
    family: "handicap",
    selections: ["HOME", "DRAW", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "ternary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "both_teams_to_score",
    name: "Both teams to score",
    sport: "football",
    family: "goals",
    selections: ["YES", "NO"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "binary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "correct_score",
    name: "Correct score",
    sport: "football",
    family: "goals",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "correct_score",
    selectionKind: "n_way",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "goal_range",
    name: "Goal range",
    sport: "football",
    family: "goals",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "range",
    selectionKind: "n_way",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "half_time_result",
    name: "Half-time result",
    sport: "football",
    family: "halves",
    selections: ["HOME", "DRAW", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "ternary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "second_half_result",
    name: "Second-half result",
    sport: "football",
    family: "halves",
    selections: ["HOME", "DRAW", "AWAY"],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "ternary",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "half_time_full_time",
    name: "Half-time / full-time",
    sport: "football",
    family: "halves",
    selections: [],
    requiresLine: false,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "enum_selection",
    selectionKind: "n_way",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "corners",
    name: "Corners (generic)",
    sport: "football",
    family: "corners",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "team_corners",
    name: "Team corners",
    sport: "football",
    family: "corners",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: true,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "corner_total",
    name: "Corner total",
    sport: "football",
    family: "corners",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "corner_handicap",
    name: "Corner handicap",
    sport: "football",
    family: "corners",
    selections: ["HOME", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "cards",
    name: "Cards (generic)",
    sport: "football",
    family: "cards",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "team_cards",
    name: "Team cards",
    sport: "football",
    family: "cards",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: true,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "card_total",
    name: "Card total",
    sport: "football",
    family: "cards",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "card_handicap",
    name: "Card handicap",
    sport: "football",
    family: "cards",
    selections: ["HOME", "AWAY"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "handicap_cover",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "shots",
    name: "Shots total",
    sport: "football",
    family: "shots",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "shots_on_target",
    name: "Shots on target",
    sport: "football",
    family: "shots",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "offsides",
    name: "Offsides",
    sport: "football",
    family: "other",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "fouls",
    name: "Fouls",
    sport: "football",
    family: "other",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "player_goals",
    name: "Player goals",
    sport: "football",
    family: "player",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: true,
    requiresTeam: false,
    outcomeType: "player_threshold",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "player_assists",
    name: "Player assists",
    sport: "football",
    family: "player",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: true,
    requiresTeam: false,
    outcomeType: "player_threshold",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "player_shots",
    name: "Player shots",
    sport: "football",
    family: "player",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: true,
    requiresTeam: false,
    outcomeType: "player_threshold",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "player_shots_on_target",
    name: "Player shots on target",
    sport: "football",
    family: "player",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: true,
    requiresTeam: false,
    outcomeType: "player_threshold",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),

  // --- Other sports catalogue stubs (not MODEL_READY) ---
  market({
    id: "basketball_total_points",
    name: "Total points",
    sport: "basketball",
    family: "goals",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["team_vs_team", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
  market({
    id: "tennis_total_games",
    name: "Total games",
    sport: "tennis",
    family: "goals",
    selections: ["OVER", "UNDER"],
    requiresLine: true,
    requiresPlayer: false,
    requiresTeam: false,
    outcomeType: "over_under",
    selectionKind: "numeric_line",
    applicableEventTypes: ["individual_vs_individual", "match"],
    readiness: "CATALOG_CAPABILITY",
  }),
]);

const MARKETS_BY_ID = new Map(MARKETS.map((item) => [item.id, item]));

export function listMarkets(): readonly MarketDefinition[] {
  return MARKETS;
}

export function getMarket(id: string): MarketDefinition | undefined {
  return MARKETS_BY_ID.get(id);
}

export function listMarketsForEventType(
  eventType: EventType,
): readonly MarketDefinition[] {
  return MARKETS.filter((item) => item.applicableEventTypes.includes(eventType));
}

export function listMarketsForSport(sportId: string): readonly MarketDefinition[] {
  const sport = getSport(sportId);
  if (!sport) {
    return [];
  }
  return MARKETS.filter((item) => {
    if (!item.applicableEventTypes.includes(sport.eventType)) {
      return false;
    }
    return item.sport === "*" || item.sport === sportId;
  });
}

export function isMarketType(value: string): value is MarketType {
  return MARKETS_BY_ID.has(value);
}

export function listMarketsByReadiness(
  readiness: MarketReadiness,
): readonly MarketDefinition[] {
  return MARKETS.filter((item) => item.readiness === readiness);
}

export function listMarketsByFamily(
  family: MarketDefinition["family"],
): readonly MarketDefinition[] {
  return MARKETS.filter((item) => item.family === family);
}
